version: '3'

services:


  rabbitmq:
    container_name: rabbitmq
    build: ./rabbitMQ
    ports:
      - "15672:15672"
      - "1883:1883"
    command: ["rabbitmq-server"]
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 2s
      retries: 20
    restart: always


  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/app
    ports:
    - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy


  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: test
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin
    ports:
    - "8086:8086"