version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-connect:
    build:
      context: ./kafka/kafka-connect
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8083:8083"
    volumes:
      - ./connect-plugins:/usr/share/confluent-hub-components

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: username
      INFLUXDB_ADMIN_PASSWORD: password

  # server:
  #   build: ./server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kafka
  #     - influxdb
  #   environment:
  #     KAFKA_BROKER_URL: kafka:9092
  #     INFLUXDB_URL: http://influxdb:8086
  #     INFLUXDB_USERNAME: username
  #     INFLUXDB_PASSWORD: password

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
